name: check
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: bluefireteam/melos-action@v3
      - run: melos format --output=none --set-exit-if-changed .
      - run: melos test
      - run: melos analyze
      - uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./coverage/lcov.info