name: publish


on:
  push:
    tags:
      - "**v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  publish-packages:
    name: Publish packages
    environment: release
    permissions:
      contents: write
      id-token: write
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dart-lang/setup-dart@v1
      - uses: bluefireteam/melos-action@v3
        with:
          publish: true