name: release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    concurrency: release
    if: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}
      - name: configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - uses: dart-lang/setup-dart@v1
      - uses: bluefireteam/melos-action@v3
        with:
          run-versioning: true
          publish-dry-run: true
          tag: true
          create-pr: false
        env:
          GH_TOKEN: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}
      - run: melos test
      - run: melos analyze
      - name: Push Tags
        run: git push --follow-tags